n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços? {}', n.isspace())
print('Possui letras e número?', n.isalnum())
print('Possui apenas números?', n.isnumeric())
print('Possui apenas letras?', n.isalpha())
print('Possui apenas letras maiúsculas?', n.isupper())
print('Possui apenas letras minúsculas?', n.islower())
print('Está capitalizada?', n.istitle())
