nome = str(input('Digite seu nome completo: ')).strip()
maiusculo = nome.upper()
minusculo = nome.lower()
letras = nome.replace(' ', '').strip()
dividido = nome.rstrip().split()
print('Nome em maiúsculo:', maiusculo)
print('Nome em minúsculo:', minusculo)
print('Comprimento do nome sem espaços:', len(letras))
print('Quantidade de letras do primeiro nome:', len(dividido [0]))
#print('Quantidade de letras do primeiro nome: {}'.format(nome.find(' ')))

